### ISSUE TITLE
Auth Error

### ISSUE THREAD

**Issue by xbelanch** [d3adwolf/rustlegacy#1]
Maybe I'm missing something but every time I try to connect to the local server it raises this auth error:

```
Server Initialized
Auth Error: invalid ticket
Auth failed: Steam auth denied user - <steam user> (<steam id>)

```
Any hint to fix it?

Best,

Xavier

**Comment by d3adwolf** [comment]
Hi Xavier,

Try to take the .dll files from the root folder of the client version of the game, which is on the site.

Judging by the error: the server is blaming the pirate user, and the root folder of the Rust server contains the original .dll files without Steam ID emulation. I hope this helps.

Regards, Dmitry

**Comment by d3adwolf** [comment]
If that doesn't help, put the Oxide module on top of the Rust server and turn off all SteamID checks in the module's configuration files.

**Comment by xbelanch** [comment]
Replacing original steam dlls of the client for the server fix this issue.

Thanks!
