### ISSUE TITLE
Sound doesn't work

### ISSUE THREAD

**Issue by xbelanch** [d3adwolf/rustlegacy#3]
Promise you that's my last bug report 🙏🏻: no audio or music. Both volume are at the maximum level:

![2022-02-17_19-02-51](https://user-images.githubusercontent.com/23429/154543178-5080e2ff-452b-45c9-9f75-fbf04b6da853.png)

Any hint or clue? I verified all the sound mixer but no luck.

Best,

Xavier

**Comment by d3adwolf** [comment]
Well, there should be an easy solution here, I think:
1. Check in the OS Windows sound settings what devices are on by default
2. Open OS Windows volume mixer and check if the game is muted

**Comment by xbelanch** [comment]
Fixed 👍🏻
