### ISSUE TITLE
missing LumaEmu.ini

### ISSUE THREAD

**Issue by catdad124** [d3adwolf/rustlegacy#4]
After launching rust.exe, get an error that says "LumaEmu.ini is missing."
![LumaEmu](https://user-images.githubusercontent.com/101141333/157109015-dde76637-5085-4d5d-93cb-0d083160c204.PNG)

**Comment by xbelanch** [comment]
Have you tried to execute "ChangeNick.exe" again?

**Comment by d3adwolf** [comment]
Reinstall Rust and don't forget to just run ChangeNick.exe before the first run.
