### ISSUE TITLE
Console Is not showing anything

### ISSUE THREAD

**Issue by Arshia1022** [d3adwolf/rustlegacy#6]
Hello.

I wanted to run the server, it does not write anything in the console and uses the CPU

Windows Server operating system

Please Help me

**Comment by vse3211** [comment]
Hi
You have GPU on your server?

**Comment by vse3211** [comment]
Send screens pls

**Comment by Arshia1022** [comment]
> Hi You have GPU on your server?

Nope

**Comment by Arshia1022** [comment]
![image](https://user-images.githubusercontent.com/89454369/227965009-24a38be1-7c04-468f-bf6a-1773cc3bff36.png)

**Comment by d3adwolf** [comment]
Either you have misconfigured something, or you have a problem with your video card drivers, even for inline graphics in the processor. You can try to run the server in Linux via Wine, many people do that.

**Comment by vse3211** [comment]
This is odd even for a missing GPU. Do you have Steam installed and running on the server? How did you change the config? Are there any plugins or mods installed on the server?

**Comment by vse3211** [comment]
How powerful is your server?

**Comment by d3adwolf** [comment]
Closed due to irrelevance.
